# Generated by Django 3.1.1 on 2020-09-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='problem_description',
            field=models.CharField(default=True, max_length=5000),
        ),
    ]
