# Generated by Django 3.1.1 on 2020-09-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_auto_20200928_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='problem_description',
            field=models.CharField(max_length=5000),
        ),
    ]
