# Generated by Django 3.1.1 on 2020-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_code_problem_sorcecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='problem_videoLink',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
