# Generated by Django 3.1.1 on 2020-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_code_problem_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='constaints',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='code',
            name='example',
            field=models.CharField(default=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='code',
            name='input_format',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='code',
            name='output_format',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='code',
            name='time_limit',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
