# Generated by Django 3.1.1 on 2020-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_auto_20200928_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='problem_sorceCode',
            field=models.TextField(default=True),
        ),
    ]
