# Generated by Django 3.1.1 on 2020-09-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_auto_20200928_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='constaints',
            field=models.TextField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='example',
            field=models.TextField(default=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='code',
            name='input_format',
            field=models.TextField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='output_format',
            field=models.TextField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='problem_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='code',
            name='problem_name',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='code',
            name='problem_videoLink',
            field=models.TextField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='time_limit',
            field=models.TextField(default=True, max_length=1000),
        ),
    ]
