# Generated by Django 3.1.1 on 2020-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_auto_20200929_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='problem_numbeer',
            field=models.IntegerField(default=0),
        ),
    ]
