# Generated by Django 3.1.1 on 2020-09-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_facts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facts',
        ),
    ]
